apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waddlebot

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - video-proxy.yaml
  - engagement.yaml
  - module-rtc.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: waddlebot
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
