apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: waddlebot

resources:
  - namespace.yaml
  - video-proxy.yaml
  - engagement.yaml
  - module-rtc.yaml

commonLabels:
  app.kubernetes.io/part-of: waddlebot
  app.kubernetes.io/managed-by: kustomize
