name: Build ai-interaction

on:
  push:
    branches: [ main, develop, 'feature/**', 'bugfix/**' ]
    paths:
      - 'action/interactive/ai_interaction_module/**'
      - 'libs/flask_core/**'
      - '.version'
      - '.github/workflows/build-ai-interaction.yml'
      - '.github/workflows/build-container.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'action/interactive/ai_interaction_module/**'
      - 'libs/flask_core/**'
  workflow_dispatch:

jobs:
  build:
    name: Build ai-interaction Container
    uses: ./.github/workflows/build-container.yml
    with:
      module_path: 'action/interactive/ai_interaction_module'
      module_name: 'ai-interaction'
      module_port: '8005'
    secrets: inherit
